server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
        
  datasource:
    name: ibooking
    url: jdbc:mysql://111.231.21.144:3306/ibooking?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: ibooking
    password: ibooking
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#  sql:
#    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
#      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huawei.ibooking.bean.po

#logging:
#  level:
#    com.huawei.ibooking: debug
